### ISSUE TITLE
WorkHourRange 新增蝴蝶蘭工時 

### ISSUE THREAD

**Issue by MatsuiLin101** [COAStatistics/alss-dev#119]
蝴蝶蘭 `Unit` 為 `盆`，`min_hour=0.061`，`max_hour=0.167`
蝴蝶蘭 `Unit` 為 `株`，`min_hour=0.042`，`max_hour=0.194`
蝴蝶蘭 `Unit` 為 其他，`min_hour=0`，`max_hour=0`

問題是product沒有紀錄`Unit`

蝴蝶蘭 `Unit` 為 `盆`

```
- model: surveys19.Product
  pk: 187
  fields:
    name: 蝴蝶蘭
    code: 704
    min_hour: 0.061
    max_hour: 0.167
    display: False
    type: 1
    management_type: 8
```

蝴蝶蘭 `Unit` 為 `株`

```
- model: surveys19.Product
  pk: 188
  fields:
    name: 蝴蝶蘭
    code: 704
    min_hour: 0.042
    max_hour: 0.194
    display: False
    type: 1
    management_type: 8
```

蝴蝶蘭 `Unit` 為 其他

```
- model: surveys19.Product
  pk: 189
  fields:
    name: 蝴蝶蘭
    code: 704
    min_hour:
    max_hour:
    display: False
    type: 1
    management_type: 8
```
